### ISSUE TITLE
todo 상태별 리스트(전체/중요/완료)

### ISSUE THREAD

**Issue by gidoldory** [gidoldory/simple-todo-app#7]
### 기능
todo 상태별 리스트(전체/중요/완료)
- 전체 : 그룹별로 등록된 모든 할일(완료 항목 제외)
- 중요 : 전체 항목 중 깃발 표시된 항목(완료 항목 제외)
- 완료 : 전체 항목 중 완료된 항목

### 작업 목록
1. [ ] props로 상태별 리스트 listType 받기(all, flag, done)
2. [ ] listType을 적용한 할일 리스트 가져오기(Redux, API)
3. [ ] 그룹명 > 리스트 형태로 view

### 예상 작업 시간
3h
